# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 're_untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import qdarkstyle
import pymysql
from PyQt5.QtWidgets import QMainWindow, QMessageBox


# import register
# import detail_mg
# import detail_st




class Ui_MainWindow(QMainWindow):
    # __init__:当前类的构造方法
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.ut = 0
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../实习项目/library项目/library/library/images/MainWindow_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 100, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 180, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 260, 241, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(460, 350, 115, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 410, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 180, 241, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(300, 350, 115, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 260, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setBaseSize(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionloading = QtWidgets.QAction(MainWindow)
        self.actionloading.setObjectName("actionloading")
        self.actionzhuce = QtWidgets.QAction(MainWindow)
        self.actionzhuce.setObjectName("actionzhuce")
        self.actiontuichudenglu = QtWidgets.QAction(MainWindow)
        self.actiontuichudenglu.setObjectName("actiontuichudenglu")
        self.actiontuichuzhuce = QtWidgets.QAction(MainWindow)
        self.actiontuichuzhuce.setObjectName("actiontuichuzhuce")
        self.menu.addSeparator()
        self.menu.addSeparator()
        self.menu.addAction(self.actionloading)
        self.menu.addAction(self.actionzhuce)
        self.menu.addAction(self.actiontuichudenglu)
        self.menu.addAction(self.actiontuichuzhuce)
        self.menubar.addAction(self.menu.menuAction())

        #事件绑定
        self.pushButton.clicked.connect(self.login)
        self.radioButton.toggled.connect(self.usertype)
        self.radioButton_2.toggled.connect(self.usertype)
        self.actionloading.triggered.connect(self.regist_user)
        self.actionzhuce.triggered.connect(self.flush)
        self.actiontuichudenglu.triggered.connect(self.flush)
        self.actiontuichuzhuce.triggered.connect(self.quit_sys)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "登录系统"))
        self.label_2.setText(_translate("MainWindow", "用户账号："))
        self.radioButton_2.setText(_translate("MainWindow", "企业·用户"))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.radioButton.setText(_translate("MainWindow", "企业·领导"))
        self.label_3.setText(_translate("MainWindow", "用户密码："))
        self.menu.setTitle(_translate("MainWindow", "菜单栏"))
        self.actionloading.setText(_translate("MainWindow", "denglu"))
        self.actionzhuce.setText(_translate("MainWindow", "zhuce"))
        self.actiontuichudenglu.setText(_translate("MainWindow", "tuichudenglu"))
        self.actiontuichuzhuce.setText(_translate("MainWindow", "tuichuxitong"))

    def login(self):
        user = self.lineEdit.text()
        pwd = self.lineEdit_2.text()
        self.usertype()
        print(self.ut)
        if (user == "" or pwd == ""):
            print(QMessageBox.warning(self, "警告", "用户名和密码不可为空!", QMessageBox.Yes, QMessageBox.Yes))
            return
        try:
            self.db = pymysql.connect(host='localhost', port=3306, user="root", password='root', database='total',
                                      charset='utf8')
        except:
            QMessageBox.warning(self, '警告', "连接数据库故障", QMessageBox.Yes)
            self.db.rollback()
        if self.ut == 1:  # 管理员用户
            sql = 'select * from manager where user_name="%s"' % user  # sql指令语句
            cur = self.db.cursor()  # 获取游标
            cur.execute(sql)  # 执行sql语句
            results = cur.fetchall()  # 通过fetchall获取数据
            print('results:', results)
            self.hide()
            # 转入主界面
            # self.libs = detail_mg.Ui_MainWindow()
            # self.libs.show()

        else:  # 普通用户
            sql = 'select * from consumer where user_name="%s"' % user  # sql指令语句
            cur = self.db.cursor()  # 获取游标
            cur.execute(sql)  # 执行sql语句
            results = cur.fetchall()  # 通过fetchall获取数据
            print('results:', results)
            self.hide()
            # 转入主界面
            # self.libs = detail_stu.Ui_MainWindow()
            # self.libs.show()

    def usertype(self):
        info = 0
        if self.radioButton.isChecked():
            self.radioButton.setChecked(True)
            info = 1
        else:
            self.radioButton.setChecked(False)
            info = 0
        if self.radioButton_2.isChecked():
            self.radioButton_2.setChecked(True)
            info = 0
        else:
            self.radioButton_2.setChecked(False)
            info = 1
        self.ut = info

    def regist_user(self):
        self.hide()  # 主界面的隐藏
        # self.regist = register.Ui_MainWindow()
        # 注册界面打开
        # self.regist.show()

    def flush(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        if self.ut == 0:
            self.radioButton.setChecked(True)

    def quit_sys(self):
        self.close()
        sys.exit()


if __name__ == '__main__':
    from PyQt5.Qt import *
    app = QtWidgets.QApplication(sys.argv) # 创建一个应用程序
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    ui1 = Ui_MainWindow()    # 创建设计好的窗口对象
    ui1.show()
    sys.exit(app.exec_())